### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by yusinan666** [ENT510/LGF_Banking#1]
![image](https://github.com/ENT510/LGF_Banking/assets/163602261/61b5bd5b-c16b-4749-b894-ee82cfec4ddc)
When I buy bank cards and deposit money, he shows that ox inventory is not exported
May I ask what stock version of ox you are using？

**Comment by ENT510** [comment]
you have not started ox inventory correctly, or you are using a version in which that export was not available

**Comment by yusinan666** [comment]
What version do you use

**Comment by ENT510** [comment]
The latest
